DROP TABLE IF EXISTS PROJECT;
CREATE TABLE PROJECT (
    ID INTEGER NOT NULL AUTO_INCREMENT
  , PID NUMBER
  , NAME VARCHAR2(5)
  , TASK VARCHAR2(5)
  , PRIMARY KEY (ID)
  , foreign key (TASK) references TASK(NAME)
);