DROP TABLE IF EXISTS TEAM;
CREATE TABLE TEAM (
    ID          INTEGER NOT NULL AUTO_INCREMENT
  , NAME VARCHAR2(5)
  , PID NUMBER
  , PRIMARY KEY (ID)
  , foreign key (PID) references PROJECT(PID)
);